name: MCP Grocy API
version: "1.2.0"
slug: mcp_grocy_api
description: Home Assistant addon for MCP server that communicates with Grocy REST API.
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
panel_icon: mdi:cart
options:
  grocy_base_url: https://your-grocy-instance.com/api
  grocy_apikey_value: your_grocy_api_key_here
  grocy_enable_ssl_verify: true
  rest_response_size_limit: 10000
schema:
  grocy_base_url: url
  grocy_apikey: password
  grocy_enable_ssl_verify: bool?
  rest_response_size_limit: int(1000,)?
image: "ghcr.io/saya6k/hassio-addons/{arch}-addon-mcp-grocy-api" # Version will be appended by build
